src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java
Tested with 2 options:
`material: placeholder-%player_item_in_hand%`
and
`material: placeholder-%string_random_DIRT,GRASS_BLOCK,DIAMOND_BLOCK,GOLD_BLOCK%`
Closes #41
=> Fixed placeholder materials being cached after first parse

src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/menu/Menu.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuHolder.java, src/main/java/com/extendedclip/deluxemenus/requirement/IsObjectRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/RequirementType.java, src/main/java/com/extendedclip/deluxemenus/requirement/StringLengthRequirement.java
This PR adds the ability to list argument validation directly in the arguments list, while also maintaining backwards compatibility.
Example: [https://paste.helpch.at/medacemeve.yaml](https://paste.helpch.at/medacemeve.yaml)
This PR also adds two new requirements to facilitate most argument validation: `is object` & `string length`.
`string length` is very simple, it takes an input, and either a `max`, a `min`, or both. Example:
```yaml
length:
type: "string length"
input: "{player}"
min: 2
max: 32
deny_commands:
- "[message] Player must be between 2 and 32 characters long."
```
`is object` is a bit more complex, but also more useful. It attempts to parse the given input as a certain type of Java object. The current options are `int`, `double`, `uuid`, and `player`. The first three are …
=> Add argument validation and `is object` + `string length` requirements

build.gradle.kts, gradle/libs.versions.toml, src/main/java/com/extendedclip/deluxemenus/DeluxeMenus.java, src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/hooks/MMOItemsHook.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java, src/main/java/com/extendedclip/deluxemenus/utils/Constants.java
This PR adds an MMOItems hook.
There is currently an issue in MMOItems that requires item creation to be done sync. This has been remedied with `Bukkit.getScheduler().callSyncMethod()`. The MMOItems developers are aware of the issue and have already deprecated the associated code [in this commit](https://gitlab.com/phoenix-dvpmt/mmoitems/-/commit/5f1e32d581590a6af8f272a526ac4023337b3868). Once that goes through, an update should be made to simplify this hook.
Closes #11
=> Add MMOItems Hook

src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java
Placeholder prefix was removed from valid material prefixes, added it back.
=> Added placeholder prefix back to valid material prefixes

src/main/java/com/extendedclip/deluxemenus/action/ClickAction.java, src/main/java/com/extendedclip/deluxemenus/action/ClickActionTask.java, src/main/java/com/extendedclip/deluxemenus/commands/DeluxeMenusCommands.java, src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/menu/Menu.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuHolder.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java, src/main/java/com/extendedclip/deluxemenus/requirement/HasExpRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/HasItemRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/HasMetaRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/HasMoneyRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/HasPermissionRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/InputResultRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/IsObjectRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/JavascriptRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/RegexMatchesRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/StringLengthRequirement.java, src/main/java/com/extendedclip/deluxemenus/utils/StringUtils.java
- Added per menu option `arguments_support_placeholders` that takes in a boolean value and defaults to `false`. When option is `false`, placeholders are not parsed inside user arguments.
- Changed how placeholders and arguments are parsed: arguments first (with placeholders inside value parsed if option mentioned above is true) and then placeholders
- Fixed placeholders not being parsed for itemhooks anymore.
=> Disable placeholders inside arguments by default + itemhook palceholder support fix

src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/menu/LoreAppendMode.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItemOptions.java
This adds the `lore_append_mode` option to items, allowing users better control over their lore. This is especially useful for servers using hooks with other plugins, as occasionally you want the items lore from those plugins but in different areas on the item in DM. An example that we ran into was our shop, were we wanted the Oraxen lore to make it easy to update DM when we change items in Oraxen. There are 4 options:
IGNORE: This makes it so that it only takes the hooked items lore
TOP: This adds the DM lore on top
BOTTOM: This adds the DM lore on the bottom
OVERRIDE: Default behavior right now, DM lore overrides hooked item lore. 
Before:
After:
Example:
```yaml
kitchen_counter_turn:
slot: 0
material: oraxen-kitchen_counter_turn
lore_append_mode: TOP
lore:
- ''
- '&f$250'
```
Feedback …
=> Add Lore Append Mode as option for menu items

src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItemOptions.java
This change adds support for customizing the light level of a [Light](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/data/type/Light.html) item. This can be done with the new `light_level` option that can take as value an integer or a placeholder.
This change was tested on:
git-Paper-365 (MC: 1.20.4)
Java 17 (OpenJDK 64-Bit Server VM 17.0.5+8)
Closes #23
=> Added support for light levels for light item

gradle/libs.versions.toml, src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItemOptions.java, src/main/java/com/extendedclip/deluxemenus/utils/ItemUtils.java, src/main/java/com/extendedclip/deluxemenus/utils/VersionHelper.java
This PR adds support for [ArmorTrims](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/meta/trim/ArmorTrim.html) and Closes https://github.com/HelpChat/DeluxeMenus/issues/55.
To use this new feature, 2 new options were added: `trim_material` and `trim_pattern`.
These options can be set for each item in each menu but will only work for armor items. Both of these options support placeholders and arguments. The options are also case-sensitive.
This change was tested on:
- git-Paper-365 (MC: 1.20.4)
- Java 17 (OpenJDK 64-Bit Server VM 17.0.5+8)
=> Added support for armor trims

src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java
=> fix: item_flags list not being handled

.gitignore, src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java, src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java, src/main/java/com/extendedclip/deluxemenus/utils/VersionHelper.java, src/main/resources/advanced_menu.yml
This PR fixes the following issues:
- Fix #115
- Fix #116 
It also deprecates the `hide_(attributes/enchantments/unbreakable)` item options in favor of `item_flags`. Users will receive a warning message in console
> Option 'hide_unbreakable' of item 'aaa' in menu 'basics_menu' is deprecated and will be removed in the future. Replace it with item_flags: [HIDE_UNBREAKABLE].
I've also improved the _unknown requirement type_ warning by also printing the value from config for easier debug.
=> fix: item flags not working in 1.20.5+ & deprecate hide_ options

src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java, src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java, src/main/java/com/extendedclip/deluxemenus/utils/ItemUtils.java
This PR removes usage of deprecate damage/data API and makes use of the more modern one that took its place. Tested in Minecraft 1.21 with Java 21.
Fixes #67
=> New `damage` option to replace `data` and swapping to the DamageAPI

src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java
Tested on Paper version 1.21-4-master@090775e, Java openjdk 21.0.3 2024-04-16 LTS
Closes #121
=> Allow enchantments to contain leading and trailing white spaces

src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/requirement/HasPermissionsRequirement.java, src/main/java/com/extendedclip/deluxemenus/requirement/RequirementType.java
https://github.com/HelpChat/DeluxeMenus/issues/141
```yml
<type>_requirement:
requirements:
perms:
type: "has permissions"
minimum: 1
permissions:
- perms.1
- perms.2
```
if `minimum` is omitted, all permissions must be met
=> Added has permissions requirement type

build.gradle.kts, gradle/libs.versions.toml, src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/hooks/BaseHeadHook.java, src/main/java/com/extendedclip/deluxemenus/hooks/ExecutableBlocksHook.java, src/main/java/com/extendedclip/deluxemenus/hooks/ExecutableItemsHook.java, src/main/java/com/extendedclip/deluxemenus/hooks/HeadDatabaseHook.java, src/main/java/com/extendedclip/deluxemenus/hooks/ItemHook.java, src/main/java/com/extendedclip/deluxemenus/hooks/ItemsAdderHook.java, src/main/java/com/extendedclip/deluxemenus/hooks/MMOItemsHook.java, src/main/java/com/extendedclip/deluxemenus/hooks/NamedHeadHook.java, src/main/java/com/extendedclip/deluxemenus/hooks/OraxenHook.java, src/main/java/com/extendedclip/deluxemenus/hooks/TextureHeadHook.java, src/main/java/com/extendedclip/deluxemenus/requirement/HasItemRequirement.java, src/main/java/com/extendedclip/deluxemenus/utils/SkullUtils.java
Examples:
```yml
<type>_requirement:
requirements:
item:
type: "has item"
material: head-Tanguygab
material: texture-f3d5e43de5d4177c4baf2f44161554473a3b0be5430998b5fcd826af943afe3
material: basehead-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjNkNWU0M2RlNWQ0MTc3YzRiYWYyZjQ0MTYxNTU0NDczYTNiMGJlNTQzMDk5OGI1ZmNkODI2YWY5NDNhZmUzIn19fQ==
material: mmoitems-<type>:<id>
material: itemsadder-<id>
```
Confirmed head, texture and basehead working, and got confirmation for mmoitems.
Others should work as well but if anyone is willing to check for ItemsAdder, HDB, Oraxen and ExecutableItems, that'd be nice
=> Add support for ItemHooks in Has Item requirement

gradle/libs.versions.toml, src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java, src/main/java/com/extendedclip/deluxemenus/menu/MenuItem.java, src/main/java/com/extendedclip/deluxemenus/menu/options/MenuItemOptions.java, src/main/java/com/extendedclip/deluxemenus/utils/VersionHelper.java
https://github.com/HelpChat/DeluxeMenus/issues/150
hide_tooltip, enchantment_glint_override, rarity, tooltip_style and item_model
Example:
```yml
items:
testItem:
slot: 0
material: DIRT
hide_tooltip: false
enchantment_glint_override: true
rarity: EPIC
#tooltip_style: <a NamespacedKey, I don't have any example for that>
item_model: minecraft:enchanted_book
```
=> Added more item tooltip stuff

src/main/java/com/extendedclip/deluxemenus/config/DeluxeMenusConfig.java
Closes #137 
Tested in Minecraft 1.21.1.
=> Register menu arguments even if the menu does not have an open command specified

src/main/java/com/extendedclip/deluxemenus/action/ClickActionTask.java, src/main/java/com/extendedclip/deluxemenus/utils/SoundUtils.java
=> Access to Sound#valueOf method through Reflection to avoid java.lang IncompatibleClassChangeError when using versions prior to 1.21.3

src/main/resources/default_menu.yml
When using the default_menu.yml example GUI the grass item does not load because the material was renamed from GRASS to SHORT_GRASS.
Do you think it is suitable to just rename it in the config or should I make it so that it is compatible for version below 1.20.3 too?
=> fix: Adjust Grass Material for Minecraft 1.20.3+ Compatibility

src/main/java/com/extendedclip/deluxemenus/command/DeluxeMenusCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/DumpCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/ExecuteCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/HelpCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/ListCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/OpenCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/ReloadCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/SubCommand.java, src/main/java/com/extendedclip/deluxemenus/menu/Menu.java
- Added tab completion for all DeluxeMenus admin commands.
- Every option is case insensitive.
While every option in tab complete is case insensitive, that is not always true during execution.
The 2 instances of this happening that I could find are menu names and the `-p:` tag for the '/dm open' command. We might want to look into making both of those case insensitive in the future.
https://github.com/user-attachments/assets/c02625be-d042-4886-a18b-7c88f60dab33
Closes #139 
Tested on: Paper version 1.21.4-164-main@8eb8e44
=> Added tab completion for all DeluxeMenus admin commands

src/main/resources/plugin.yml
This PR addresses an issue where the MMOItems integration doesn't work properly for many users because DeluxeMenus loads before MMOItems.
=> add mmoitems as softdepend

src/main/java/com/extendedclip/deluxemenus/action/ClickActionTask.java, src/main/java/com/extendedclip/deluxemenus/command/DeluxeMenusCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/ExecuteCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/HelpCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/ListCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/MetaCommand.java, src/main/java/com/extendedclip/deluxemenus/command/subcommand/SubCommand.java, src/main/java/com/extendedclip/deluxemenus/config/GeneralConfig.java, src/main/java/com/extendedclip/deluxemenus/persistentmeta/DataAction.java, src/main/java/com/extendedclip/deluxemenus/persistentmeta/DataType.java, src/main/java/com/extendedclip/deluxemenus/persistentmeta/PersistentMetaHandler.java, src/main/java/com/extendedclip/deluxemenus/placeholder/Expansion.java, src/main/java/com/extendedclip/deluxemenus/requirement/HasMetaRequirement.java, src/main/java/com/extendedclip/deluxemenus/utils/DumpUtils.java, src/main/java/com/extendedclip/deluxemenus/utils/Messages.java, src/main/java/com/extendedclip/deluxemenus/utils/PaginationUtils.java, src/main/java/com/extendedclip/deluxemenus/utils/Pair.java
This PR improves the current PDC usage and adds new commands for handling use metadata.
Added:
- Commands for handling metadata (with support for placeholders):
- `show`: Gets the stored value at the specified key as long as it matches the specified type
- `list`: List all key-value pairs of a specified type
- `set`: Set a value of specified type at the specified key (if a value exists at the given key, it will override it only if the type matches)
- `remove`: Remove a value of specified type from the specified key (as long as existent value matches the given type)
- `add`: Used for addition on number types (If no value exists at the given key yet, the addition will be done on a 0 value)
- `subtract`: Used for subtraction on number types (If no value exists at the given key yet, the …
=> Improve metadata / PDC usage

src/main/java/com/extendedclip/deluxemenus/persistentmeta/PersistentMetaHandler.java
This PR fixes a class cast exception that occurs when trying to add INTEGER or LONG meta.
=> Fix exception that occurs when trying to add metadata.

src/main/java/com/extendedclip/deluxemenus/action/ActionType.java, src/main/java/com/extendedclip/deluxemenus/action/ClickActionTask.java
This PR introduces a new `[log]` action to enable logging custom messages directly to the console, which is particularly useful for debugging and monitoring player actions. The logged message is prefixed with the menus name which is logging it, or `Unknown Menu` if the holder is empty.
Syntax: ```[log] [level] [message]```
Parameters:
- `[level]`: can be any valid `java.util.logging.Level` (e.g., `INFO`, `WARNING`, `SEVERE`). If an invalid level is provided, it defaults to `INFO`.
- `[message]`: The message to output to console, supports placeholders.
=> Add [log] Action to Output Console Messages for Debugging/Testing, Closes #199

gradle/libs.versions.toml
Fixes `[minimessage]` components having issues with `<click>` components for me and probably some other issues on 1.21.8
=> Update Adventure API
